package hibernate;
// Generated 2017-7-10 16:57:49 by Hibernate Tools 4.3.1.Final

/**
 * Plan generated by hbm2java
 */
public class Plan implements java.io.Serializable {

	private Integer id;
	private Train train;
	private Station station;
	private Integer gnumber;
	private Integer compare;
	private String con1;
	private String con2;
	private String con3;
	private String con4;
	private String con5;

	public Plan() {
	}

	public Plan(Integer id, Train train, Integer gnumber, Integer compare) {
		this.id = id;
		this.train = train;
		this.gnumber = gnumber;
		this.compare = compare;
	}

	public Plan(Integer id, Train train, Station station, Integer gnumber, Integer compare, String con1, String con2,
			String con3, String con4, String con5) {
		this.id = id;
		this.train = train;
		this.station = station;
		this.gnumber = gnumber;
		this.compare = compare;
		this.con1 = con1;
		this.con2 = con2;
		this.con3 = con3;
		this.con4 = con4;
		this.con5 = con5;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Train getTrain() {
		return this.train;
	}

	public void setTrain(Train train) {
		this.train = train;
	}

	public Station getStation() {
		return this.station;
	}

	public void setStation(Station station) {
		this.station = station;
	}

	public Integer getGnumber() {
		return this.gnumber;
	}

	public void setGnumber(Integer gnumber) {
		this.gnumber = gnumber;
	}

	public Integer getCompare() {
		return this.compare;
	}

	public void setCompare(Integer compare) {
		this.compare = compare;
	}

	public String getCon1() {
		return this.con1;
	}

	public void setCon1(String con1) {
		this.con1 = con1;
	}

	public String getCon2() {
		return this.con2;
	}

	public void setCon2(String con2) {
		this.con2 = con2;
	}

	public String getCon3() {
		return this.con3;
	}

	public void setCon3(String con3) {
		this.con3 = con3;
	}

	public String getCon4() {
		return this.con4;
	}

	public void setCon4(String con4) {
		this.con4 = con4;
	}

	public String getCon5() {
		return this.con5;
	}

	public void setCon5(String con5) {
		this.con5 = con5;
	}

}
