package hibernate;
// Generated 2017-7-10 16:57:49 by Hibernate Tools 4.3.1.Final



/**
 * Price generated by hbm2java
 */
public class Price implements java.io.Serializable {

	private Integer id;
	private Integer traintype;
	private Integer trainbodytype;
	private Integer seattype;
	private Double rate;
	private Integer scale;
	private String con1;
	private String con2;
	private String con3;
	private String con4;
	private String con5;

	public Price() {
	}

	public Price(Integer id, Integer traintype, Integer trainbodytype, Integer seattype, Double rate, Integer scale) {
		this.id = id;
		this.traintype = traintype;
		this.trainbodytype = trainbodytype;
		this.seattype = seattype;
		this.rate = rate;
		this.scale = scale;
	}

	public Price(Integer id, Integer traintype, Integer trainbodytype, Integer seattype, Double rate, Integer scale, String con1,
			String con2, String con3, String con4, String con5) {
		this.id = id;
		this.traintype = traintype;
		this.trainbodytype = trainbodytype;
		this.seattype = seattype;
		this.rate = rate;
		this.scale = scale;
		this.con1 = con1;
		this.con2 = con2;
		this.con3 = con3;
		this.con4 = con4;
		this.con5 = con5;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getTraintype() {
		return this.traintype;
	}

	public void setTraintype(Integer traintype) {
		this.traintype = traintype;
	}

	public Integer getTrainbodytype() {
		return this.trainbodytype;
	}

	public void setTrainbodytype(Integer trainbodytype) {
		this.trainbodytype = trainbodytype;
	}

	public Integer getSeattype() {
		return this.seattype;
	}

	public void setSeattype(Integer seattype) {
		this.seattype = seattype;
	}

	public Double getRate() {
		return this.rate;
	}

	public void setRate(Double rate) {
		this.rate = rate;
	}

	public Integer getScale() {
		return this.scale;
	}

	public void setScale(Integer scale) {
		this.scale = scale;
	}

	public String getCon1() {
		return this.con1;
	}

	public void setCon1(String con1) {
		this.con1 = con1;
	}

	public String getCon2() {
		return this.con2;
	}

	public void setCon2(String con2) {
		this.con2 = con2;
	}

	public String getCon3() {
		return this.con3;
	}

	public void setCon3(String con3) {
		this.con3 = con3;
	}

	public String getCon4() {
		return this.con4;
	}

	public void setCon4(String con4) {
		this.con4 = con4;
	}

	public String getCon5() {
		return this.con5;
	}

	public void setCon5(String con5) {
		this.con5 = con5;
	}

}
