package hibernate;
// Generated 2017-7-10 16:57:49 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Station generated by hbm2java
 */
public class Station implements java.io.Serializable {

	private String id;
	private String name;
	private String pinyin;
	private String region;
	private Integer range;
	private String company;
	private String address;
	private String con1;
	private String con2;
	private String con3;
	private String con4;
	private String con5;
	private Set plans = new HashSet(0);
	private Set trainsForStartstation = new HashSet(0);
	private Set trainsForEndstation = new HashSet(0);

	public Station() {
	}

	public Station(String id, String name, String pinyin, String region, Integer range, String company, String address) {
		this.id = id;
		this.name = name;
		this.pinyin = pinyin;
		this.region = region;
		this.range = range;
		this.company = company;
		this.address = address;
	}
	public Station(String id, String name, String pinyin, String region) {
		this.id = id;
		this.name = name;
		this.pinyin = pinyin;
		this.region = region;
	}

	public Station(String id, String name, String pinyin, String region, Integer range, String company, String address,
			String con1, String con2, String con3, String con4, String con5, Set plans, Set trainsForStartstation,
			Set trainsForEndstation) {
		this.id = id;
		this.name = name;
		this.pinyin = pinyin;
		this.region = region;
		this.range = range;
		this.company = company;
		this.address = address;
		this.con1 = con1;
		this.con2 = con2;
		this.con3 = con3;
		this.con4 = con4;
		this.con5 = con5;
		this.plans = plans;
		this.trainsForStartstation = trainsForStartstation;
		this.trainsForEndstation = trainsForEndstation;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPinyin() {
		return this.pinyin;
	}

	public void setPinyin(String pinyin) {
		this.pinyin = pinyin;
	}

	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public Integer getRange() {
		return this.range;
	}

	public void setRange(Integer range) {
		this.range = range;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCon1() {
		return this.con1;
	}

	public void setCon1(String con1) {
		this.con1 = con1;
	}

	public String getCon2() {
		return this.con2;
	}

	public void setCon2(String con2) {
		this.con2 = con2;
	}

	public String getCon3() {
		return this.con3;
	}

	public void setCon3(String con3) {
		this.con3 = con3;
	}

	public String getCon4() {
		return this.con4;
	}

	public void setCon4(String con4) {
		this.con4 = con4;
	}

	public String getCon5() {
		return this.con5;
	}

	public void setCon5(String con5) {
		this.con5 = con5;
	}

	public Set getPlans() {
		return this.plans;
	}

	public void setPlans(Set plans) {
		this.plans = plans;
	}

	public Set getTrainsForStartstation() {
		return this.trainsForStartstation;
	}

	public void setTrainsForStartstation(Set trainsForStartstation) {
		this.trainsForStartstation = trainsForStartstation;
	}

	public Set getTrainsForEndstation() {
		return this.trainsForEndstation;
	}

	public void setTrainsForEndstation(Set trainsForEndstation) {
		this.trainsForEndstation = trainsForEndstation;
	}

}
